name: vtIL
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ipython
  - jupyter
  - ipykernel
  - pyqt
  - opencv
  - scikit-learn
  - h5py
  - pillow
  - imageio
  - tqdm
  - requests
  - pyyaml
  - setuptools
  - wheel
  # PyTorch + CUDA 12.1 (convenient and compatible)
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - cudnn
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.5.2
    - arrow==1.3.0
    - attrs==24.2.0
    - boto3==1.35.93
    - botocore==1.35.93
    - cachetools==5.5.0
    - cloudpickle==3.1.0
    - configargparse==1.7
    - evdev==1.7.1
    - flask==3.0.3
    - gitpython==3.1.44
    - huggingface-hub==0.28.1
    - hydra-core==1.3.2
    - jinja2==3.1.3
    - matplotlib==3.7.5
    - mujoco==3.1.0
    - open3d==0.18.0
    - openai==1.63.2
    - pybullet==3.2.6
    - pyk4a==1.5.0
    - pyopengl==3.1.7
    - pyrealsense2==2.55.1.6486
    - pyyaml==6.0.2
    - tensorboard-data-server==0.7.2
    - tensordict==0.5.0
    - torch==2.4.1
    - torchvision==0.19.1
    - torchaudio==2.4.1
    - transformers==4.46.3
    - wandb==0.19.1
prefix: /home/rzhao/miniconda3/envs/vtIL