name: vtIL
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=7.33.0=py38h578d9bd_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py38h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.8.20=he870216_0
  - python_abi=3.8=2_cp38
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.1=py38h0a891b7_3
  - traitlets=5.14.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.5.2
    - arrow==1.3.0
    - attrs==24.2.0
    - blinker==1.8.2
    - boto3==1.35.93
    - botocore==1.35.93
    - bravado==11.0.3
    - bravado-core==6.1.1
    - cachetools==5.5.0
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - cloudpickle==3.1.0
    - configargparse==1.7
    - contourpy==1.1.1
    - cycler==0.12.1
    - dash==2.18.2
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - easydict==1.13
    - egl-probe==1.0.2
    - etils==1.3.0
    - eval-type-backport==0.2.2
    - evdev==1.7.1
    - exceptiongroup==1.2.2
    - fastjsonschema==2.21.1
    - filelock==3.13.1
    - flask==3.0.3
    - fonttools==4.55.2
    - fqdn==1.5.1
    - fsspec==2024.2.0
    - future==1.0.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - glfw==2.8.0
    - google-api-python-client==2.154.0
    - google-auth==2.36.0
    - google-auth-httplib2==0.2.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.69.0
    - h11==0.14.0
    - h5py==3.11.0
    - hidapi==0.14.0.post4
    - httpcore==1.0.7
    - httplib2==0.22.0
    - httpx==0.28.1
    - huggingface-hub==0.28.1
    - hydra-core==1.3.2
    - idna==3.10
    - imageio==2.35.1
    - imageio-ffmpeg==0.5.1
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - ipywidgets==8.1.5
    - iso8601==2.1.0
    - isoduration==20.11.0
    - itsdangerous==2.2.0
    - jinja2==3.1.3
    - jiter==0.8.2
    - jmespath==1.0.1
    - joblib==1.4.2
    - jsonpointer==3.0.0
    - jsonref==1.1.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.7
    - llvmlite==0.41.1
    - loguru==0.7.3
    - markdown==3.7
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - monotonic==1.6
    - mpmath==1.3.0
    - msgpack==1.1.0
    - mujoco==3.1.0
    - nbformat==5.10.4
    - neptune==1.13.0
    - networkx==3.0
    - numba==0.58.1
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.1.105
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - open3d==0.18.0
    - openai==1.63.2
    - opencv-python==4.10.0.84
    - orjson==3.10.12
    - pandas==2.0.3
    - pillow==10.4.0
    - pkgutil-resolve-name==1.3.10
    - plotly==5.24.1
    - protobuf==3.13.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pybullet==3.2.6
    - pydantic==2.10.4
    - pydantic-core==2.27.2
    - pyjwt==2.9.0
    - pyk4a==1.5.0
    - pynput==1.7.7
    - pyopengl==3.1.7
    - pyparsing==3.1.4
    - pyqt5==5.15.11
    - pyqt5-qt5==5.15.16
    - pyqt5-sip==12.15.0
    - pyquaternion==0.9.9
    - pyrealsense2==2.55.1.6486
    - pyserial==3.5
    - python-dateutil==2.9.0.post0
    - python-xlib==0.33
    - pytz==2024.2
    - pywavelets==1.4.1
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - retrying==1.3.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.20.1
    - rsa==4.9
    - s3transfer==0.10.4
    - safetensors==0.5.2
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - sentry-sdk==2.19.2
    - setproctitle==1.3.4
    - setuptools==75.3.0
    - simplejson==3.19.3
    - six==1.17.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - swagger-spec-validator==3.0.4
    - sympy==1.13.1
    - tenacity==9.0.0
    - tensorboard-data-server==0.7.2
    - tensordict==0.5.0
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - tokenizers==0.20.3
    - torch==2.4.1+cu121
    - torchaudio==2.4.1+cu121
    - torchvision==0.19.1+cu121
    - tqdm==4.67.1
    - transformers==4.46.3
    - triton==3.0.0
    - types-python-dateutil==2.9.0.20241206
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - uri-template==1.3.0
    - uritemplate==4.1.1
    - urllib3==1.26.20
    - wandb==0.19.1
    - webcolors==24.8.0
    - websocket-client==1.8.0
    - werkzeug==3.0.6
    - widgetsnbextension==4.0.13
    - zipp==3.20.2
prefix: /home/rzhao/miniconda3/envs/vtIL
